// <auto-generated />
using System;
using Bake.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bake.Migrations
{
    [DbContext(typeof(BakeContext))]
    partial class BakeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bake.Models.AccountStatusDefinition", b =>
                {
                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("status_id");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("PK__Account___3683B531C403EB5D");

                    b.ToTable("Account_Status_Definitions", "User");
                });

            modelBuilder.Entity("Bake.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("url");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("OrderId");

                    b.ToTable("Notifications", "Service");
                });

            modelBuilder.Entity("Bake.Models.Platform.PaymentStatusDefinition", b =>
                {
                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("status_id");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("PK__Payment___3683B531856E8AD6");

                    b.ToTable("Payment_Status_Definitions", "Platform");
                });

            modelBuilder.Entity("Bake.Models.Platform.PaymentTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("OrdersId")
                        .HasColumnType("int")
                        .HasColumnName("orders_id");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<byte>("TransactionStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("transaction_status");

                    b.HasKey("TransactionId")
                        .HasName("PK__Payment___85C600AF79EB0C0D");

                    b.HasIndex("OrdersId");

                    b.HasIndex("TransactionStatus");

                    b.ToTable("Payment_Transactions", "Platform");
                });

            modelBuilder.Entity("Bake.Models.Platform.PlatformEscrowLedger", b =>
                {
                    b.Property<int>("LedgerId")
                        .HasColumnType("int")
                        .HasColumnName("ledger_id");

                    b.Property<decimal>("HeldAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("held_amount");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<byte>("PaymentStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("payment_status");

                    b.HasKey("LedgerId")
                        .HasName("PK__Platform__97EDEDA129A989F6");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentStatus");

                    b.ToTable("Platform_Escrow_Ledger", "Platform");
                });

            modelBuilder.Entity("Bake.Models.Platform.RoleStatusDefinition", b =>
                {
                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("status_id");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("PK__Role_Sta__3683B5311F0212F8");

                    b.ToTable("Role_Status_Definitions", "User");
                });

            modelBuilder.Entity("Bake.Models.Platform.SellerWallet", b =>
                {
                    b.Property<int>("PayoutId")
                        .HasColumnType("int")
                        .HasColumnName("payout_id");

                    b.Property<string>("BankRefId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("bank_ref_id");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("fee");

                    b.Property<byte>("PayoutStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("payout_status");

                    b.Property<decimal>("SellerAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("seller_amount");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("PayoutId")
                        .HasName("PK__Seller_W__3B0771EC01AAF1C9");

                    b.HasIndex("PayoutStatus");

                    b.HasIndex("UserId");

                    b.ToTable("Seller_Wallet", "Platform");
                });

            modelBuilder.Entity("Bake.Models.Platform.SellerWalletStatusDefinition", b =>
                {
                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("status_id");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("PK__Seller_W__3683B531B5D0DB1F");

                    b.ToTable("Seller_Wallet_Status_Definitions", "Platform");
                });

            modelBuilder.Entity("Bake.Models.Platform.SystemMetadatum", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastLoginIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("last_login_ip");

                    b.Property<string>("RegisterIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("register_ip");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("PK__System_M__B9BE370F6E92A76A");

                    b.ToTable("System_Metadata", "User");
                });

            modelBuilder.Entity("Bake.Models.Platform.TransactionStatusDefinition", b =>
                {
                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("status_id");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("PK__Transact__3683B531D5616479");

                    b.ToTable("Transaction_Status_Definitions", "Platform");
                });

            modelBuilder.Entity("Bake.Models.Sales.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cart_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CartId")
                        .HasName("PK__Cart__2EF52A278338B2D9");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Cart", "Sales");
                });

            modelBuilder.Entity("Bake.Models.Sales.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cart_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("cart_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int")
                        .HasColumnName("product_quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("CartItemId")
                        .HasName("PK__CartItem__5D9A6C6E165A4511");

                    b.HasIndex("CartId");

                    b.ToTable("CartItem", "Sales");
                });

            modelBuilder.Entity("Bake.Models.Sales.CartStatus", b =>
                {
                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("status_id");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("PK__Cart_Sta__3683B531F40F6FF0");

                    b.ToTable("Cart_Status", "Sales");
                });

            modelBuilder.Entity("Bake.Models.Sales.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<byte>("PaymentMethodId")
                        .HasColumnType("tinyint")
                        .HasColumnName("payment_method");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("shipping_address");

                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("status_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__4659622948DE6D11");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", "Sales");
                });

            modelBuilder.Entity("Bake.Models.Sales.OrderItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("int")
                        .HasColumnName("item_quantity");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("unit_price");

                    b.HasKey("ItemId")
                        .HasName("PK__Order_It__52020FDD1BE8135E");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_Order_Items_product_id");

                    b.ToTable("Order_Items", "Sales");
                });

            modelBuilder.Entity("Bake.Models.Sales.OrderStatus", b =>
                {
                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("status_id");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("PK__Order_St__3683B531F0F39FA7");

                    b.ToTable("Order_Status", "Sales");
                });

            modelBuilder.Entity("Bake.Models.Sales.PaymentMethod", b =>
                {
                    b.Property<byte>("PaymentMethodId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PaymentMethodId");

                    b.ToTable("PaymentMethod", "Sales");

                    b.HasData(
                        new
                        {
                            PaymentMethodId = (byte)0,
                            Name = "信用卡"
                        },
                        new
                        {
                            PaymentMethodId = (byte)1,
                            Name = "轉帳"
                        },
                        new
                        {
                            PaymentMethodId = (byte)2,
                            Name = "貨到付款"
                        });
                });

            modelBuilder.Entity("Bake.Models.Sales.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("ProductDate")
                        .HasColumnType("datetime")
                        .HasColumnName("product_date");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product_description");

                    b.Property<string>("ProductImage")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("product_image");

                    b.Property<string>("ProductMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("product_method");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("product_name");

                    b.Property<decimal?>("ProductRating")
                        .HasColumnType("decimal(2, 1)")
                        .HasColumnName("product_rating");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ProductId")
                        .HasName("PK__Products__47027DF5901740A0");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Products", "Sales");
                });

            modelBuilder.Entity("Bake.Models.Sales.ProductCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("category_description");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.HasKey("CategoryId")
                        .HasName("PK_Prodeuct_Category");

                    b.ToTable("Product_Category", "Sales");
                });

            modelBuilder.Entity("Bake.Models.Sales.ProductDetail", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime")
                        .HasColumnName("expire_date");

                    b.Property<decimal?>("ProductDiscount")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("product_discount");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("product_price");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int")
                        .HasColumnName("product_quantity");

                    b.HasKey("ProductId")
                        .HasName("PK__Product___47027DF5C980F170");

                    b.ToTable("Product_Details", "Sales");
                });

            modelBuilder.Entity("Bake.Models.Sales.ProductIngredient", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("Ingredients")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ingredients");

                    b.Property<string>("NetWeight")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("net_weight");

                    b.Property<string>("ShelfLifeNote")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("shelf_life_note");

                    b.HasKey("ProductId")
                        .HasName("PK_Product_Ingredient");

                    b.ToTable("Product_Ingredients", "Sales");
                });

            modelBuilder.Entity("Bake.Models.Sales.ProductReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<byte>("UserRating")
                        .HasColumnType("tinyint")
                        .HasColumnName("user_rating");

                    b.HasKey("ReviewId")
                        .HasName("PK__Product___60883D90B2F109EB");

                    b.HasIndex("UserId");

                    b.ToTable("Product_Review", "Service");
                });

            modelBuilder.Entity("Bake.Models.Sales.Refund", b =>
                {
                    b.Property<int>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("refund_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefundId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("refund_amount");

                    b.Property<byte>("RefundStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("refund_status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("RefundId")
                        .HasName("PK__Refund__897E9EA304602809");

                    b.HasIndex("OrderId");

                    b.HasIndex("RefundStatus");

                    b.ToTable("Refund", "Sales");
                });

            modelBuilder.Entity("Bake.Models.Sales.RefundStatusDefinition", b =>
                {
                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("status_id");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("PK__Refund_S__3683B531B6C2B1EB");

                    b.ToTable("Refund_Status_Definition", "Sales");
                });

            modelBuilder.Entity("Bake.Models.Sales.Shop", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("facebook_url");

                    b.Property<string>("InstagramUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("instagram_url");

                    b.Property<string>("PinterestUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("pinterest_url");

                    b.Property<DateTime>("SellerApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("seller_approved_at");

                    b.Property<string>("ShopDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("shop_description");

                    b.Property<string>("ShopImg")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("shop_img");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("shop_name");

                    b.Property<decimal>("ShopRating")
                        .HasColumnType("decimal(2, 1)")
                        .HasColumnName("shop_rating");

                    b.Property<DateTime>("ShopTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("shop_time")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("status_id");

                    b.Property<string>("YoutubeUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("youtube_url");

                    b.HasKey("UserId")
                        .HasName("PK__Shop__B9BE370F36C4789E");

                    b.HasIndex("StatusId");

                    b.ToTable("Shop", "Sales");
                });

            modelBuilder.Entity("Bake.Models.Sales.ShopStatus", b =>
                {
                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("status_id");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("PK__Shop_Sta__3683B53184C3F953");

                    b.ToTable("Shop_Status", "Sales");
                });

            modelBuilder.Entity("Bake.Models.Service.ChatMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("message_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("message");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("sender_id");

                    b.HasKey("MessageId")
                        .HasName("PK__Chat_Mes__0BBF6EE670CE81C2");

                    b.HasIndex("RoomId");

                    b.HasIndex("SenderId");

                    b.ToTable("Chat_Message", "Service");
                });

            modelBuilder.Entity("Bake.Models.Service.ChatRoom", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<byte>("RoomType")
                        .HasColumnType("tinyint")
                        .HasColumnName("room_type");

                    b.HasKey("RoomId")
                        .HasName("PK__Chat_Roo__19675A8A5EAF03AF");

                    b.HasIndex("RoomType");

                    b.ToTable("Chat_Room", "Service");
                });

            modelBuilder.Entity("Bake.Models.Service.ChatRoomMember", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("joined_at");

                    b.HasKey("RoomId", "UserId")
                        .HasName("PK__Chat_Roo__F2FCB9FA646E7D20");

                    b.HasIndex("UserId");

                    b.ToTable("Chat_Room_Member", "Service");
                });

            modelBuilder.Entity("Bake.Models.Service.ChatRoomType", b =>
                {
                    b.Property<byte>("TypeId")
                        .HasColumnType("tinyint")
                        .HasColumnName("type_id");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type_name");

                    b.HasKey("TypeId")
                        .HasName("PK_Chat_Room_Type");

                    b.ToTable("Chat_Room_Type", "Service");

                    b.HasData(
                        new
                        {
                            TypeId = (byte)0,
                            TypeName = "一對一"
                        },
                        new
                        {
                            TypeId = (byte)1,
                            TypeName = "群組"
                        },
                        new
                        {
                            TypeId = (byte)2,
                            TypeName = "AI客服"
                        });
                });

            modelBuilder.Entity("Bake.Models.Service.NotifyType", b =>
                {
                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("status_id");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("PK__Notify_T__3683B5318DF87776");

                    b.ToTable("Notify_Type", "Service");
                });

            modelBuilder.Entity("Bake.Models.Service.SystemNotify", b =>
                {
                    b.Property<int>("NotifyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notify_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotifyId"));

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("content_text");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<byte>("NotifyType")
                        .HasColumnType("tinyint")
                        .HasColumnName("notify_type");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int")
                        .HasColumnName("recipient_id");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("sender_id");

                    b.HasKey("NotifyId")
                        .HasName("PK__System_N__DD351C96AB33B043");

                    b.HasIndex("NotifyType");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("System_Notify", "Service");
                });

            modelBuilder.Entity("Bake.Models.Social.EventDetail", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<DateTime>("EventEndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("event_end_time");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("event_time");

                    b.Property<byte>("EventTypeId")
                        .HasColumnType("tinyint")
                        .HasColumnName("event_type_id");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("location_address");

                    b.Property<string>("LocationCity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("location_city");

                    b.Property<byte>("ManualStatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("manual_status_id");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int")
                        .HasColumnName("max_participants");

                    b.Property<int?>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<int?>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("price");

                    b.Property<DateTime>("SignupDeadline")
                        .HasColumnType("datetime2")
                        .HasColumnName("signup_deadline");

                    b.Property<DateTime>("SignupStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("signup_start");

                    b.HasKey("EventId")
                        .HasName("PK__Event_De__2370F7274139FFD8");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("ManualStatusId");

                    b.HasIndex("PostId");

                    b.ToTable("Event_Details", "Social");
                });

            modelBuilder.Entity("Bake.Models.Social.EventRegistration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("registration_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("notes");

                    b.Property<int>("NumParticipants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("num_participants");

                    b.Property<byte>("RegistStatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("regist_status_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("RegistrationId")
                        .HasName("PK__Event_Re__22A298F68C7318A2");

                    b.HasIndex("EventId");

                    b.HasIndex("RegistStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Event_Registrations", "Social");
                });

            modelBuilder.Entity("Bake.Models.Social.EventStatusLookup", b =>
                {
                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("status_id");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("PK__Event_St__3683B531FAE7C579");

                    b.ToTable("Event_Status_Lookup", "Social");
                });

            modelBuilder.Entity("Bake.Models.Social.EventTypeLookup", b =>
                {
                    b.Property<byte>("EventTypeId")
                        .HasColumnType("tinyint")
                        .HasColumnName("event_type_id");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("event_type_name");

                    b.HasKey("EventTypeId")
                        .HasName("PK__Event_Ty__BB84C6F37D26A3D8");

                    b.ToTable("Event_Type_Lookup", "Social");
                });

            modelBuilder.Entity("Bake.Models.Social.Follow", b =>
                {
                    b.Property<int>("FollowerId")
                        .HasColumnType("int")
                        .HasColumnName("follower_id");

                    b.Property<int>("BefollowedId")
                        .HasColumnType("int")
                        .HasColumnName("befollowed_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("FollowerId", "BefollowedId")
                        .HasName("PK__Follows__ED9DDEC41E3954E9");

                    b.HasIndex("BefollowedId");

                    b.ToTable("Follows", "Social");
                });

            modelBuilder.Entity("Bake.Models.Social.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("FavoriteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("favorite_count");

                    b.Property<bool?>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<int?>("LikesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("likes_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<byte>("TypeId")
                        .HasColumnType("tinyint")
                        .HasColumnName("type_id");

                    b.Property<int?>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.HasKey("PostId")
                        .HasName("PK__Posts__3ED78766908ED1D3");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TypeId");

                    b.ToTable("Posts", "Social");
                });

            modelBuilder.Entity("Bake.Models.Social.PostAttachment", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("image_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("AltText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("alt_text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("file_url");

                    b.Property<bool?>("IsCover")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_cover");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<int?>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("ImageId")
                        .HasName("PK__Post_Att__DC9AC955774B700E");

                    b.HasIndex("PostId");

                    b.ToTable("Post_Attachments", "Social");
                });

            modelBuilder.Entity("Bake.Models.Social.PostComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_comment_id");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("CommentId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Post_Comments", "Social");
                });

            modelBuilder.Entity("Bake.Models.Social.PostFavorite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId", "PostId")
                        .HasName("PK__Post_Fav__CA534F79346BBFD2");

                    b.HasIndex("PostId");

                    b.ToTable("Post_Favorites", "Social");
                });

            modelBuilder.Entity("Bake.Models.Social.PostLike", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId", "PostId")
                        .HasName("PK__Post_Lik__CA534F79CE46A682");

                    b.HasIndex("PostId");

                    b.ToTable("Post_Likes", "Social");
                });

            modelBuilder.Entity("Bake.Models.Social.PostTypeLookup", b =>
                {
                    b.Property<byte>("TypeId")
                        .HasColumnType("tinyint")
                        .HasColumnName("type_id");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type_name");

                    b.HasKey("TypeId")
                        .HasName("PK__Post_Typ__2C0005987B9A8CC3");

                    b.ToTable("Post_Type_Lookup", "Social");
                });

            modelBuilder.Entity("Bake.Models.Social.RegistStatusLookup", b =>
                {
                    b.Property<byte>("RegStatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("reg_status_id");

                    b.Property<string>("RegStatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("reg_status_name");

                    b.HasKey("RegStatusId")
                        .HasName("PK__Regist_S__E15399458474C6B6");

                    b.ToTable("Regist_Status_Lookup", "Social");
                });

            modelBuilder.Entity("Bake.Models.Social.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tag_name");

                    b.HasKey("TagId")
                        .HasName("PK__Tags__4296A2B63A112AAE");

                    b.HasIndex(new[] { "TagName" }, "UQ__Tags__E298655C3498945A")
                        .IsUnique();

                    b.ToTable("Tags", "Social");
                });

            modelBuilder.Entity("Bake.Models.User.AccountAuth", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<byte>("AccountStatus")
                        .HasColumnType("tinyint")
                        .HasColumnName("account_status");

                    b.Property<string>("ConfirmationToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("confirmation_token");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("email_verified_at");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("is_email_confirmed");

                    b.Property<bool>("IsSeller")
                        .HasColumnType("bit")
                        .HasColumnName("is_seller");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint")
                        .HasColumnName("role");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId")
                        .HasName("PK__Account___B9BE370F373FAEB4");

                    b.HasIndex("AccountStatus");

                    b.HasIndex("Role");

                    b.HasIndex(new[] { "UserName" }, "UQ__Account___7C9273C4B53441EF")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Account___AB6E616446F1839A")
                        .IsUnique();

                    b.ToTable("Account_Auth", "User");
                });

            modelBuilder.Entity("Bake.Models.User.UserGenderStatusDefinition", b =>
                {
                    b.Property<byte>("StatusId")
                        .HasColumnType("tinyint")
                        .HasColumnName("status_id");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("PK__User_Gen__3683B531490A5DAD");

                    b.ToTable("User_Gender_Status_Definitions", "User");
                });

            modelBuilder.Entity("Bake.Models.User.UserPaymentSecret", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("EncryptedBankAcc")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("encrypted_bank_acc");

                    b.HasKey("UserId")
                        .HasName("PK__User_Pay__B9BE370F7A61D912");

                    b.ToTable("User_Payment_Secrets", "Platform");
                });

            modelBuilder.Entity("Bake.Models.User.UserProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("bio");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Persona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("persona");

                    b.Property<DateTime>("UserBirthdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("user_birthdate");

                    b.Property<byte>("UserGender")
                        .HasColumnType("tinyint")
                        .HasColumnName("user_gender");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("user_phone");

                    b.HasKey("UserId")
                        .HasName("PK__User_Pro__B9BE370FA505BCCE");

                    b.HasIndex("UserGender");

                    b.ToTable("User_Profile", "User");
                });

            modelBuilder.Entity("PostTagMapping", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.HasKey("PostId", "TagId")
                        .HasName("PK__Post_Tag__4AFEED4D6A1B85AD");

                    b.HasIndex("TagId");

                    b.ToTable("Post_Tag_Mapping", "Social");
                });

            modelBuilder.Entity("Bake.Models.Notification", b =>
                {
                    b.HasOne("Bake.Models.Sales.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Notification_Orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Bake.Models.Platform.PaymentTransaction", b =>
                {
                    b.HasOne("Bake.Models.Sales.Order", "Orders")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("OrdersId")
                        .IsRequired()
                        .HasConstraintName("FK_Pay_Orders");

                    b.HasOne("Bake.Models.Platform.TransactionStatusDefinition", "TransactionStatusNavigation")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("TransactionStatus")
                        .IsRequired()
                        .HasConstraintName("FK_Pay_Status");

                    b.Navigation("Orders");

                    b.Navigation("TransactionStatusNavigation");
                });

            modelBuilder.Entity("Bake.Models.Platform.PlatformEscrowLedger", b =>
                {
                    b.HasOne("Bake.Models.Sales.Order", "Order")
                        .WithMany("PlatformEscrowLedgers")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Ledger_Orders");

                    b.HasOne("Bake.Models.Platform.PaymentStatusDefinition", "PaymentStatusNavigation")
                        .WithMany("PlatformEscrowLedgers")
                        .HasForeignKey("PaymentStatus")
                        .IsRequired()
                        .HasConstraintName("FK_Ledger_Status");

                    b.Navigation("Order");

                    b.Navigation("PaymentStatusNavigation");
                });

            modelBuilder.Entity("Bake.Models.Platform.SellerWallet", b =>
                {
                    b.HasOne("Bake.Models.Platform.SellerWalletStatusDefinition", "PayoutStatusNavigation")
                        .WithMany("SellerWallets")
                        .HasForeignKey("PayoutStatus")
                        .IsRequired()
                        .HasConstraintName("FK_Wallet_Status");

                    b.HasOne("Bake.Models.Sales.Shop", "User")
                        .WithMany("SellerWallets")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Wallet_Shop");

                    b.Navigation("PayoutStatusNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bake.Models.Platform.SystemMetadatum", b =>
                {
                    b.HasOne("Bake.Models.User.AccountAuth", "User")
                        .WithOne("SystemMetadatum")
                        .HasForeignKey("Bake.Models.Platform.SystemMetadatum", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_System_Metadata_Auth");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bake.Models.Sales.Cart", b =>
                {
                    b.HasOne("Bake.Models.Sales.CartStatus", "StatusNavigation")
                        .WithMany("Carts")
                        .HasForeignKey("Status")
                        .IsRequired()
                        .HasConstraintName("FK_cart_Status");

                    b.HasOne("Bake.Models.User.UserProfile", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_cart_Profile");

                    b.Navigation("StatusNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bake.Models.Sales.CartItem", b =>
                {
                    b.HasOne("Bake.Models.Sales.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .IsRequired()
                        .HasConstraintName("FK_cartItem_cart");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Bake.Models.Sales.Order", b =>
                {
                    b.HasOne("Bake.Models.Sales.PaymentMethod", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bake.Models.Sales.OrderStatus", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Status");

                    b.HasOne("Bake.Models.User.UserProfile", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Profile");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bake.Models.Sales.OrderItem", b =>
                {
                    b.HasOne("Bake.Models.Sales.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Items_Orders");

                    b.HasOne("Bake.Models.Sales.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Items_Products");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bake.Models.Sales.Product", b =>
                {
                    b.HasOne("Bake.Models.Sales.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Products_Prodeuct_Category");

                    b.HasOne("Bake.Models.User.AccountAuth", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Products_Auth");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bake.Models.Sales.ProductDetail", b =>
                {
                    b.HasOne("Bake.Models.Sales.Product", "Product")
                        .WithOne("ProductDetail")
                        .HasForeignKey("Bake.Models.Sales.ProductDetail", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bake.Models.Sales.ProductIngredient", b =>
                {
                    b.HasOne("Bake.Models.Sales.Product", "Product")
                        .WithOne("ProductIngredient")
                        .HasForeignKey("Bake.Models.Sales.ProductIngredient", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Ingredient_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bake.Models.Sales.ProductReview", b =>
                {
                    b.HasOne("Bake.Models.User.UserProfile", "User")
                        .WithMany("ProductReviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Review_Profile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bake.Models.Sales.Refund", b =>
                {
                    b.HasOne("Bake.Models.Sales.Order", "Order")
                        .WithMany("Refunds")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_refund_Orders");

                    b.HasOne("Bake.Models.Sales.RefundStatusDefinition", "RefundStatusNavigation")
                        .WithMany("Refunds")
                        .HasForeignKey("RefundStatus")
                        .IsRequired()
                        .HasConstraintName("FK_refund_Status");

                    b.Navigation("Order");

                    b.Navigation("RefundStatusNavigation");
                });

            modelBuilder.Entity("Bake.Models.Sales.Shop", b =>
                {
                    b.HasOne("Bake.Models.Sales.ShopStatus", "Status")
                        .WithMany("Shops")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Shop_Status");

                    b.HasOne("Bake.Models.User.AccountAuth", "User")
                        .WithOne("Shop")
                        .HasForeignKey("Bake.Models.Sales.Shop", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Shop_Auth");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bake.Models.Service.ChatMessage", b =>
                {
                    b.HasOne("Bake.Models.Service.ChatRoom", "Room")
                        .WithMany("ChatMessages")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK_Message_Room");

                    b.HasOne("Bake.Models.User.UserProfile", "Sender")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("FK_Message_Profile");

                    b.Navigation("Room");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Bake.Models.Service.ChatRoom", b =>
                {
                    b.HasOne("Bake.Models.Service.ChatRoomType", "RoomTypeNavigation")
                        .WithMany("ChatRooms")
                        .HasForeignKey("RoomType")
                        .IsRequired()
                        .HasConstraintName("FK_Room_Type");

                    b.Navigation("RoomTypeNavigation");
                });

            modelBuilder.Entity("Bake.Models.Service.ChatRoomMember", b =>
                {
                    b.HasOne("Bake.Models.Service.ChatRoom", "Room")
                        .WithMany("ChatRoomMembers")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK_Member_Room");

                    b.HasOne("Bake.Models.User.UserProfile", "User")
                        .WithMany("ChatRoomMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Member_Profile");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bake.Models.Service.SystemNotify", b =>
                {
                    b.HasOne("Bake.Models.Service.NotifyType", "NotifyTypeNavigation")
                        .WithMany("SystemNotifies")
                        .HasForeignKey("NotifyType")
                        .IsRequired()
                        .HasConstraintName("FK_Notify_Type");

                    b.HasOne("Bake.Models.User.UserProfile", "Recipient")
                        .WithMany("SystemNotifyRecipients")
                        .HasForeignKey("RecipientId")
                        .IsRequired()
                        .HasConstraintName("FK_Notify_Recipient");

                    b.HasOne("Bake.Models.User.UserProfile", "Sender")
                        .WithMany("SystemNotifySenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK_Notify_Sender");

                    b.Navigation("NotifyTypeNavigation");

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Bake.Models.Social.EventDetail", b =>
                {
                    b.HasOne("Bake.Models.Social.EventTypeLookup", "EventType")
                        .WithMany("EventDetails")
                        .HasForeignKey("EventTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Event_Type");

                    b.HasOne("Bake.Models.Social.EventStatusLookup", "ManualStatus")
                        .WithMany("EventDetails")
                        .HasForeignKey("ManualStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Event_Status");

                    b.HasOne("Bake.Models.Social.Post", "Post")
                        .WithMany("EventDetails")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Event_Post");

                    b.Navigation("EventType");

                    b.Navigation("ManualStatus");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Bake.Models.Social.EventRegistration", b =>
                {
                    b.HasOne("Bake.Models.Social.EventDetail", "Event")
                        .WithMany("EventRegistrations")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK_Reg_Event");

                    b.HasOne("Bake.Models.Social.RegistStatusLookup", "RegistStatus")
                        .WithMany("EventRegistrations")
                        .HasForeignKey("RegistStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Reg_Status");

                    b.HasOne("Bake.Models.User.UserProfile", "User")
                        .WithMany("EventRegistrations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Reg_Profile");

                    b.Navigation("Event");

                    b.Navigation("RegistStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bake.Models.Social.Follow", b =>
                {
                    b.HasOne("Bake.Models.User.UserProfile", "Befollowed")
                        .WithMany("FollowBefolloweds")
                        .HasForeignKey("BefollowedId")
                        .IsRequired()
                        .HasConstraintName("FK_Befollowed_Profile");

                    b.HasOne("Bake.Models.User.UserProfile", "Follower")
                        .WithMany("FollowFollowers")
                        .HasForeignKey("FollowerId")
                        .IsRequired()
                        .HasConstraintName("FK_Follower_Profile");

                    b.Navigation("Befollowed");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("Bake.Models.Social.Post", b =>
                {
                    b.HasOne("Bake.Models.User.UserProfile", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_Posts_Profile");

                    b.HasOne("Bake.Models.Social.PostTypeLookup", "Type")
                        .WithMany("Posts")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Posts_Type");

                    b.Navigation("Author");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Bake.Models.Social.PostAttachment", b =>
                {
                    b.HasOne("Bake.Models.Social.Post", "Post")
                        .WithMany("PostAttachments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Attach_Post");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Bake.Models.Social.PostComment", b =>
                {
                    b.HasOne("Bake.Models.Social.PostComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Bake.Models.Social.Post", "Post")
                        .WithMany("PostComments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bake.Models.User.UserProfile", "User")
                        .WithMany("PostComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bake.Models.Social.PostFavorite", b =>
                {
                    b.HasOne("Bake.Models.Social.Post", "Post")
                        .WithMany("PostFavorites")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_Favorites_Post");

                    b.HasOne("Bake.Models.User.UserProfile", "User")
                        .WithMany("PostFavorites")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Favorites_Profile");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bake.Models.Social.PostLike", b =>
                {
                    b.HasOne("Bake.Models.Social.Post", "Post")
                        .WithMany("PostLikes")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_Likes_Post");

                    b.HasOne("Bake.Models.User.UserProfile", "User")
                        .WithMany("PostLikes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Likes_Profile");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bake.Models.User.AccountAuth", b =>
                {
                    b.HasOne("Bake.Models.AccountStatusDefinition", "AccountStatusNavigation")
                        .WithMany("AccountAuths")
                        .HasForeignKey("AccountStatus")
                        .IsRequired()
                        .HasConstraintName("FK_Account_Auth_Account_Status");

                    b.HasOne("Bake.Models.Platform.RoleStatusDefinition", "RoleNavigation")
                        .WithMany("AccountAuths")
                        .HasForeignKey("Role")
                        .IsRequired()
                        .HasConstraintName("FK_Account_Auth_Role_Status");

                    b.Navigation("AccountStatusNavigation");

                    b.Navigation("RoleNavigation");
                });

            modelBuilder.Entity("Bake.Models.User.UserPaymentSecret", b =>
                {
                    b.HasOne("Bake.Models.User.AccountAuth", "User")
                        .WithOne("UserPaymentSecret")
                        .HasForeignKey("Bake.Models.User.UserPaymentSecret", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Secret_Auth");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bake.Models.User.UserProfile", b =>
                {
                    b.HasOne("Bake.Models.User.UserGenderStatusDefinition", "UserGenderNavigation")
                        .WithMany("UserProfiles")
                        .HasForeignKey("UserGender")
                        .IsRequired()
                        .HasConstraintName("FK_User_Profile_Gender");

                    b.HasOne("Bake.Models.User.AccountAuth", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("Bake.Models.User.UserProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Profile_Auth");

                    b.Navigation("User");

                    b.Navigation("UserGenderNavigation");
                });

            modelBuilder.Entity("PostTagMapping", b =>
                {
                    b.HasOne("Bake.Models.Social.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Mapping_Post");

                    b.HasOne("Bake.Models.Social.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Mapping_Tag");
                });

            modelBuilder.Entity("Bake.Models.AccountStatusDefinition", b =>
                {
                    b.Navigation("AccountAuths");
                });

            modelBuilder.Entity("Bake.Models.Platform.PaymentStatusDefinition", b =>
                {
                    b.Navigation("PlatformEscrowLedgers");
                });

            modelBuilder.Entity("Bake.Models.Platform.RoleStatusDefinition", b =>
                {
                    b.Navigation("AccountAuths");
                });

            modelBuilder.Entity("Bake.Models.Platform.SellerWalletStatusDefinition", b =>
                {
                    b.Navigation("SellerWallets");
                });

            modelBuilder.Entity("Bake.Models.Platform.TransactionStatusDefinition", b =>
                {
                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("Bake.Models.Sales.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Bake.Models.Sales.CartStatus", b =>
                {
                    b.Navigation("Carts");
                });

            modelBuilder.Entity("Bake.Models.Sales.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("PaymentTransactions");

                    b.Navigation("PlatformEscrowLedgers");

                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("Bake.Models.Sales.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Bake.Models.Sales.PaymentMethod", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Bake.Models.Sales.Product", b =>
                {
                    b.Navigation("ProductDetail");

                    b.Navigation("ProductIngredient");
                });

            modelBuilder.Entity("Bake.Models.Sales.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Bake.Models.Sales.RefundStatusDefinition", b =>
                {
                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("Bake.Models.Sales.Shop", b =>
                {
                    b.Navigation("SellerWallets");
                });

            modelBuilder.Entity("Bake.Models.Sales.ShopStatus", b =>
                {
                    b.Navigation("Shops");
                });

            modelBuilder.Entity("Bake.Models.Service.ChatRoom", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("ChatRoomMembers");
                });

            modelBuilder.Entity("Bake.Models.Service.ChatRoomType", b =>
                {
                    b.Navigation("ChatRooms");
                });

            modelBuilder.Entity("Bake.Models.Service.NotifyType", b =>
                {
                    b.Navigation("SystemNotifies");
                });

            modelBuilder.Entity("Bake.Models.Social.EventDetail", b =>
                {
                    b.Navigation("EventRegistrations");
                });

            modelBuilder.Entity("Bake.Models.Social.EventStatusLookup", b =>
                {
                    b.Navigation("EventDetails");
                });

            modelBuilder.Entity("Bake.Models.Social.EventTypeLookup", b =>
                {
                    b.Navigation("EventDetails");
                });

            modelBuilder.Entity("Bake.Models.Social.Post", b =>
                {
                    b.Navigation("EventDetails");

                    b.Navigation("PostAttachments");

                    b.Navigation("PostComments");

                    b.Navigation("PostFavorites");

                    b.Navigation("PostLikes");
                });

            modelBuilder.Entity("Bake.Models.Social.PostComment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Bake.Models.Social.PostTypeLookup", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Bake.Models.Social.RegistStatusLookup", b =>
                {
                    b.Navigation("EventRegistrations");
                });

            modelBuilder.Entity("Bake.Models.User.AccountAuth", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Shop");

                    b.Navigation("SystemMetadatum");

                    b.Navigation("UserPaymentSecret");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Bake.Models.User.UserGenderStatusDefinition", b =>
                {
                    b.Navigation("UserProfiles");
                });

            modelBuilder.Entity("Bake.Models.User.UserProfile", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("ChatMessages");

                    b.Navigation("ChatRoomMembers");

                    b.Navigation("EventRegistrations");

                    b.Navigation("FollowBefolloweds");

                    b.Navigation("FollowFollowers");

                    b.Navigation("Orders");

                    b.Navigation("PostComments");

                    b.Navigation("PostFavorites");

                    b.Navigation("PostLikes");

                    b.Navigation("Posts");

                    b.Navigation("ProductReviews");

                    b.Navigation("SystemNotifyRecipients");

                    b.Navigation("SystemNotifySenders");
                });
#pragma warning restore 612, 618
        }
    }
}
